/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import server.Student;

/**
 *
 * @author Admin
 */
public class frmSinhVien extends javax.swing.JFrame {

	/**
	 * Creates new form frmSinhVien
	 */
	public frmSinhVien() {
		initComponents();
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
                javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
                javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
                txtHoTen = new javax.swing.JTextField();
                javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
                txtMSSV = new javax.swing.JTextField();
                javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
                txtDToan = new javax.swing.JTextField();
                txtDTA = new javax.swing.JTextField();
                javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
                txtDVan = new javax.swing.JTextField();
                javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
                btnGui = new javax.swing.JButton();
                javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
                tblSinhVien = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Thông Tin Sinh Viên");
                setResizable(false);

                jPanel1.setBackground(new java.awt.Color(153, 255, 255));

                jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
                jLabel1.setText("Thông Tin Sinh Viên");

                jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
                jLabel2.setText("Họ và Tên:");

                jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
                jLabel3.setText("MSSV:");

                jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
                jLabel4.setText("Điểm Toán:");

                jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
                jLabel5.setText("Điểm Tiếng Anh:");
                jLabel5.setToolTipText("");

                jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
                jLabel6.setText("Điểm Văn:");

                btnGui.setBackground(new java.awt.Color(255, 255, 153));
                btnGui.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
                btnGui.setText("Gửi");
                btnGui.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnGuiActionPerformed(evt);
                        }
                });

                tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Họ Tên", "MSSV", "Điểm Toán", "Điểm Văn", "Điểm TA", "Điểm TB"
                        }
                ));
                jScrollPane1.setViewportView(tblSinhVien);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(117, 117, 117)
                                                                .addComponent(jLabel1))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(40, 40, 40)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel3)
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(txtMSSV, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(txtHoTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(btnGui, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                                                .addComponent(txtDToan)
                                                                                .addComponent(txtDTA)
                                                                                .addComponent(txtDVan, javax.swing.GroupLayout.Alignment.LEADING)))))
                                                .addGap(0, 59, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                        .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtDVan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDToan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDTA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGui)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
                byte []send;
		DatagramSocket client;
		try {
			client = new DatagramSocket();
			String hoTen = this.txtHoTen.getText();
			String mssv = this.txtMSSV.getText();
			float diemToan = Float.parseFloat(txtDToan.getText());
			float diemVan = Float.parseFloat(txtDVan.getText());
			float diemTA = Float.parseFloat(txtDTA.getText());
			String chuoi = "SendFromSinhVien#"+hoTen+"#"+mssv+"#"+diemToan+"#"+diemVan+"#"+diemTA;
			send = chuoi.getBytes();
			InetAddress ip = InetAddress.getByName("localhost");
			DatagramPacket sendData = new DatagramPacket(send, send.length, ip, 1234);
			client.send(sendData);
			
			byte[] receiveBuffer = new byte[65507];
			DatagramPacket receiveData = new DatagramPacket(receiveBuffer, receiveBuffer.length);
			client.receive(receiveData);
			
			String  receive = new String(receiveData.getData()).trim();
			System.out.println(receive);
			String[] s = receive.split("#");	
			
			Student st = new Student();
			st.setHoTen(s[0]);
			st.setMssv(s[1]);
			st.setDiemToan(Float.parseFloat(s[2]));
			st.setDiemVan(Float.parseFloat(s[3]));
			st.setDiemTA(Float.parseFloat(s[4]));
			Float dtb = Float.parseFloat(s[5]);
			
			DefaultTableModel tblModel = (DefaultTableModel) tblSinhVien.getModel();
			tblModel.addRow(new Object[] {st.getHoTen(), st.getMssv(), st.getDiemToan(), st.getDiemVan(), st.getDiemTA(), dtb});
			JOptionPane.showMessageDialog(null, "Điểm trung bình = "+dtb);
		} catch (Exception e) {
			e.printStackTrace();
		}
        }//GEN-LAST:event_btnGuiActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frmSinhVien().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnGui;
        private javax.swing.JTable tblSinhVien;
        private javax.swing.JTextField txtDTA;
        private javax.swing.JTextField txtDToan;
        private javax.swing.JTextField txtDVan;
        private javax.swing.JTextField txtHoTen;
        private javax.swing.JTextField txtMSSV;
        // End of variables declaration//GEN-END:variables
}
